// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Example: typeof import('./src/components/example.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RAppApp: typeof import('!app/app')['default']
    RAppHello: typeof import('!app/hello')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}
